[project]
name = "forecasting-mcp"
version = "0.1.0"
description = "MCP server for LLM clients to interact with my forecasting website"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
    "requests>=2.32.3",
]
